spring.datasource.url=jdbc:postgresql://postgres:5432/skillsync_auth
spring.datasource.username=postgres
spring.datasource.password=Pavan@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=redis
spring.data.redis.port=6379
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
jwt.secret=SkillSync@SecretKey#2024VeryLongAndSecureMustBe256Bits
jwt.expiration=86400000
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
