spring.datasource.url=jdbc:postgresql://postgres:5432/skillsync_review
spring.datasource.username=postgres
spring.datasource.password=Pavan@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
feign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.mentorService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.mentorService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.mentorService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.mentorService.waitDurationInOpenState=10s
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
